[package]
name = "ra"
version = "0.1.0"
authors = ["tkgsy <meirvg@gmail.com>"]

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
log = ''
env_logger = ''

[dependencies.pnet]
version = "0.20.0"